[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = [ "r2d2","postgres"] }
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.204"
dotenvy = "0.15"
chrono = "0.4.4"
jsonwebtoken = "9.3.0"
bcrypt = "0.15.1"


